---
- hosts: webserver
  tasks:
###############################################################################
# COPYING FILES

    - name: Check if file exists
      stat:
        path: /root/sample.tx
      register: p

    - debug:
        msg: "Path exists and is a File"
      when: p.stat.isreg is defined and p.stat.isreg
    - debug:
        msg: "Path doesn't exist"
      when: p.stat.isreg is not defined
