---
- hosts: webserver
  vars:

    ###########################################################################
    # The following variables depend on local machine. DEFINE THEM
    # inputfile will be given as input
    cur_dir: /home/abhishek/Desktop/major
    ##########################################################################
    metadata_dir: "{{cur_dir}}/temp_metadata"
    chunk_dir: "{{cur_dir}}/temp_chunk"
    script_dir: "{{cur_dir}}/script"

    chunk_size: 1024


    server_cur_dir: /root/major
    server_chunk_dir: "{{server_cur_dir}}/chunk"
    server_metadata_dir: "{{server_cur_dir}}/metadata"
    server_temp_metadata_dir: "{{server_cur_dir}}/temp_metadata"


  tasks:
    #- name: pinging server
    #  ping:

    - name: creating chunk directory
      local_action: file path={{chunk_dir}} state=directory

    - name: creating metadata directory
      local_action: file path={{metadata_dir}} state=directory

    - name: Compiling ByteMergeAndSplit.java
      local_action: shell javac {{script_dir}}/ByteMergeAndSplit.java
      register: out
    - debug: var=out.stdout_lines

    - name: Compiling hash.java
      local_action: shell javac {{script_dir}}/hash.java
      register: out
    - debug: var=out.stdout_lines

    - name: Splitting file into chunks
      local_action: shell java -classpath {{script_dir}} ByteMergeAndSplit split {{inputfile}} {{chunk_dir}} {{chunk_size}}

    - name: Generating hashlist of chunks
      local_action: script {{script_dir}}/generate_hashlist.sh {{inputfile}}
      register: out
      ignore_errors: yes
    - debug: var=out.stdout_lines
      when: out.rc == 0

    - fail:
        msg: "Failed to generate Hashlist!"
      when: out.rc !=0

    - name: preparing server
      file:
        path: "{{server_temp_metadata_dir}}"
        state: directory
        mode: 0755

    - set_fact:
        hashlist_src: "{{metadata_dir}}/{{inputfile}}.hashlist"
    - set_fact:
        hashlist_dest: "{{server_temp_metadata_dir}}/{{inputfile}}.hashlist"
    - name: Sending hashlist to server
      copy:
        src: "{{hashlist_src}}"
        dest: "{{hashlist_dest}}"
