---
- hosts: webserver
  vars_files:
  - vars.yml

  tasks:
###############################################################################
# PREPARING LOCAL MACHINE

    - name: preparing server
      file:
        path: "{{server_temp_metadata_dir}}"
        state: directory
        mode: 0755

    - file:
        path: "{{server_cur_dir}}"
        state: directory
        mode: 0755

    - file:
        path: "{{server_chunk_dir}}"
        state: directory
        mode: 0755

    - file:
        path: "{{server_metadata_dir}}"
        state: directory
        mode: 0755

    - name: Preparing local machine
      local_action: file path={{chunk_dir}} state=directory

    - local_action: file path={{metadata_dir}} state=directory

    - local_action: shell javac {{script_dir}}/ByteMergeAndSplit.java
      register: out
    - debug: var=out.stdout_lines

    - local_action: shell javac {{script_dir}}/hash.java
      register: out
    - debug: var=out.stdout_lines


###############################################################################
# PERFORMING TASKS

    - name: Splitting file into chunks
      local_action: shell java -classpath {{script_dir}} ByteMergeAndSplit split {{inputfile}} {{chunk_dir}} {{chunk_size}}

    - name: Generating hashlist of chunks
      local_action: script {{script_dir}}/generate_hashlist.sh {{inputfile}}
      register: out
    - debug: var=out.stdout_lines


    - name: Sending hashlist to server
      copy:
        src: "{{metadata_dir}}/{{inputfile}}.hashlist"
        dest: "{{server_temp_metadata_dir}}/{{inputfile}}.hashlist"

    # The path below is NOT ABSOLUTE . Its RELATIVE.
    - name: Processing hashlist on server
      script: srv_process_hashlist.sh "{{inputfile}}"
      register: out
    - debug: var=out.stdout_lines

    - name: Fetching list of new chunks
      fetch:
       src: "{{server_temp_metadata_dir}}/{{inputfile}}.hashlist.new"
       dest: "{{metadata_dir}}/{{inputfile}}.hashlist.new"

    - name: Fetching list of old chunks
      fetch:
       src: "{{server_temp_metadata_dir}}/{{inputfile}}.hashlist.old"
       dest: "{{metadata_dir}}/{{inputfile}}.hashlist.old"
       flat: yes

###############################################################################
 # Tasks below are for cleanup

    - local_action: file path="{{script_dir}}/ByteMergeAndSplit.class" state=absent

    - local_action: file path="{{script_dir}}/hash.class" state=absent
